### ISSUE TITLE
install_agent.sh with DD_HOST_TAGS breaks datadog.yaml configuration file

### ISSUE THREAD

**Issue by bpicode** [DataDog/datadog-unix-agent#131]
Hi,
I am not sure, if this is the correct repository to report this issue.

When I execute the script (I got it from https://s3.amazonaws.com/dd-agent/scripts/install_script.sh) with the environment variable `DD_HOST_TAGS=foo:bar` it seems that the resulting configuration file `datadog.yaml` is broken.

I traced the problem to [install_script.sh#L239-L243](https://github.com/DataDog/datadog-unix-agent/blob/master/scripts/install_script.sh#L239-L243) where the command
```
"sed \"s|# tags:.*|tags: "$formatted_host_tags"/\" $CONF"
```
"uncomments" the [correct part in datadog.yaml](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml#L131-L133) but unfortunately also [some other part](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml#L978-L980) related to snmp configuration.

Since that other part is in the "middle of nowhere", where all surrounding config is still commented, this results in a configuration file that the datadog agent cannot parse.

It would be great if this issue could be fixed.

Cheers.

**Comment by chouetz** [comment]
Hi @bpicode, many thanks for reporting this.
Can you confirm you faced the issue with a version of install_script strictly less than 1.7.1?
The [fix](https://github.com/DataDog/agent-linux-install-script/pull/45) was merged in version 1.7.1. Besides we will soon add some test to validate the configuration files we generate by install_script are valid parseable yaml.
Don't hesitate to tell me if something is still wrong.
Thanks in advance and sorry for the inconvenience

**Comment by bpicode** [comment]
Hi @chouetz.
I can confirm that I faced the issue with the script available at https://s3.amazonaws.com/dd-agent/scripts/install_script.sh.
When I download it right now, it seems that it is still the old version, which caused the problem.

**Comment by chouetz** [comment]
Hi @bpicode,

There might be a version mismatch somewhere:
- If you are using the AIX version of the Agent, you should use [this install_script](https://raw.githubusercontent.com/DataDog/datadog-unix-agent/master/scripts/install_script.sh), as per our [documentation](https://app.datadoghq.com/account/settings#agent/aix)
- If you are using a Linux version of the Agent you should use [this version](https://s3.amazonaws.com/dd-agent/scripts/install_script_agent7.sh), (e.g. Debian [documentation](https://app.datadoghq.com/account/settings#agent/debian) which points to the latest released version (note the script name **install_script_agent[67].sh**, and not install_script.sh)

Could this explain why you faced the issue?

**Comment by bpicode** [comment]
Hi @chouetz,
using [install_script_agent7.sh](https://s3.amazonaws.com/dd-agent/scripts/install_script_agent7.sh) worked for me.
Thank you very much for the hint. Closing this issue.
